web_api_app_env_TUNING: true
web_api_app_env_DEBUG: true
web_api_app_env_EXTERNAL_URL: "https://dev/approve"
web_api_app_env_CLIENT: "dev_client_external"
web_api_app_env_INTERACTION_MODE: "API"
web_api_app_env_DEVICE_ID: 2346456

web_api_docker_image: daniel1302/devops-task-api:v0.0.1
web_api_replicas: 3